### ISSUE TITLE
Needed to adjust from Serial1 to Serial to get an output on the serial monitor

### ISSUE THREAD

**Issue by gregorwolf** [pinae/ESP8266-Dash#2]
I've needed to replace Serial1 with Serial throughout the whole file to get an output to the serial monitor.

**Comment by pinae** [comment]
The ESP8266 has two serial ports. However the ESP-01 only exposes the primary one. If you want to receive debug messages through this port you have to use `Serial` as you pointed out. If you use another Module like the ESP-12 you can read debug messages from `Serial1` while keeping the main serial connection for uploads of new versions. This setup speeds up the development and that's what I did.
